<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { isEvaluationReport, type EvaluationReport, type MetricValue } from '../evaluation-report'

const props = defineProps<{ locale: 'zh' | 'en' }>()

type GateState = 'PASS' | 'FAIL' | 'NOT_MEASURED'

interface ScoreMetric {
  key: string
  label: string
  helper: string
  metric: MetricValue | undefined
  threshold?: number
  direction?: 'min' | 'max'
}

const report = ref<EvaluationReport | null>(null)
const loading = ref(false)
const loadError = ref('')
const source = ref<'published' | 'local'>('published')
const fileInput = ref<HTMLInputElement | null>(null)

const copy = computed(() => props.locale === 'zh' ? {
  kicker: 'EVALUATION SCORECARD',
  title: '评测评分总览',
  lede: '展示离线评测器生成的真实分层指标。Case Success 是主结果，安全门禁不会被平均分抵消。',
  latest: '刷新最新结果',
  import: '导入 summary.json',
  loading: '正在读取评测结果…',
  empty: '尚未发布评测结果。你可以导入 evaluation/report 生成的 summary.json。',
  synthetic: '当前是合成 smoke fixture，仅用于验证评分链路，不代表真实 benchmark。',
  local: '本地导入',
  published: '已发布结果',
  caseSuccess: 'Case Success Rate',
  eligible: '有效 cases',
  successful: '成功 cases',
  excluded: '排除 cases',
  confidence: 'Wilson 95% CI',
  releaseGate: '发布门禁',
  incomplete: '指标未完整',
  run: 'Run',
  dataset: 'Dataset',
  strategy: 'Strategy',
  measuredAt: 'Measured at',
  retrieval: '检索与排序',
  generation: '回答质量',
  safety: '安全门禁',
  performance: '性能与稳定性',
  cases: 'Case 明细',
  caseId: 'Case ID',
  result: '结果',
  reason: '失败原因',
  noReason: '全部必要条件通过',
  pass: '通过',
  fail: '失败',
  notMeasured: '未测量',
  noCases: '当前报告没有 case 级明细。',
  methodology: '评分由 Python evaluator 计算；页面只负责读取和展示，不会在浏览器里伪造或重新平均指标。',
  invalidFile: '文件不是有效的 EnterpriseRAG summary.json。',
  loadFailed: '无法读取已发布的评测结果。',
  forbidden: '禁止文档泄漏',
  injections: '提示注入服从',
  hardGate: 'ACL / 引用硬门禁',
  p95: 'P95 延迟',
  errors: '请求错误率',
  fallback: 'Fallback 率',
} : {
  kicker: 'EVALUATION SCORECARD',
  title: 'Evaluation scorecard',
  lede: 'Real layered metrics emitted by the offline evaluator. Case Success is primary and safety gates cannot be averaged away.',
  latest: 'Refresh latest',
  import: 'Import summary.json',
  loading: 'Loading evaluation results…',
  empty: 'No evaluation result is published yet. Import a summary.json generated by evaluation/report.',
  synthetic: 'This is a synthetic smoke fixture for validating the scoring path, not a benchmark result.',
  local: 'Local import',
  published: 'Published result',
  caseSuccess: 'Case Success Rate',
  eligible: 'eligible cases',
  successful: 'successful cases',
  excluded: 'excluded cases',
  confidence: 'Wilson 95% CI',
  releaseGate: 'Release gate',
  incomplete: 'Metrics incomplete',
  run: 'Run',
  dataset: 'Dataset',
  strategy: 'Strategy',
  measuredAt: 'Measured at',
  retrieval: 'Retrieval & ranking',
  generation: 'Answer quality',
  safety: 'Security gates',
  performance: 'Performance & reliability',
  cases: 'Case details',
  caseId: 'Case ID',
  result: 'Result',
  reason: 'Failure reason',
  noReason: 'All required conditions passed',
  pass: 'Pass',
  fail: 'Fail',
  notMeasured: 'Not measured',
  noCases: 'This report does not contain case-level details.',
  methodology: 'Scores are computed by the Python evaluator. The page reads and presents them without inventing or re-averaging metrics in the browser.',
  invalidFile: 'The file is not a valid EnterpriseRAG summary.json.',
  loadFailed: 'Unable to load the published evaluation result.',
  forbidden: 'Forbidden retrievals',
  injections: 'Prompt injection compliance',
  hardGate: 'ACL / citation hard gate',
  p95: 'P95 latency',
  errors: 'Request error rate',
  fallback: 'Fallback rate',
})

const reportUrl = (import.meta.env.VITE_EVALUATION_REPORT_URL || '/evaluation/latest.json').trim()
const retrieval = computed(() => report.value?.layers?.retrieval)
const generation = computed(() => report.value?.layers?.generation)
const success = computed(() => generation.value?.case_success)
const security = computed(() => report.value?.layers?.security)
const performance = computed(() => report.value?.layers?.performance)
const successRate = computed(() => success.value?.success_rate ?? null)
const successCi = computed(() => success.value?.ci95 ?? null)
const judgeResult = computed(() => generation.value?.judge?.results?.find((item) => item.metric === 'faithfulness' && item.status === 'MEASURED'))

const retrievalScores = computed<ScoreMetric[]>(() => [
  { key: 'recall5', label: 'Recall@5', helper: 'gold evidence found in top 5', metric: retrieval.value?.ks?.['5']?.recall, threshold: 0.85, direction: 'min' },
  { key: 'ndcg10', label: 'nDCG@10', helper: 'ranking quality across relevant docs', metric: retrieval.value?.ks?.['10']?.ndcg, threshold: 0.80, direction: 'min' },
  { key: 'mrr10', label: 'MRR@10', helper: 'rank of the first relevant result', metric: retrieval.value?.ks?.['10']?.mrr },
  { key: 'hit5', label: 'HitRate@5', helper: 'cases with at least one relevant hit', metric: retrieval.value?.ks?.['5']?.hit_rate },
])

const generationScores = computed<ScoreMetric[]>(() => [
  { key: 'facts', label: 'Fact coverage', helper: 'required facts present in the answer', metric: generation.value?.fact_coverage },
  { key: 'token', label: 'Token F1', helper: 'token overlap with the gold answer', metric: generation.value?.token_f1 },
  { key: 'exact', label: 'Exact match', helper: 'normalized answer equals gold', metric: generation.value?.exact_match },
  { key: 'faith', label: 'Faithfulness', helper: judgeResult.value?.reason || 'optional DeepEval judge', metric: judgeResult.value ? { value: judgeResult.value.score } : undefined, threshold: judgeResult.value?.threshold ?? 0.90, direction: 'min' },
])

const measuredGates = computed(() => [...retrievalScores.value, ...generationScores.value]
  .filter((item) => item.threshold !== undefined && item.metric?.value != null)
  .map((item) => metricGate(item)))

const releaseGate = computed<'PASS' | 'FAIL' | 'INCOMPLETE'>(() => {
  if (security.value?.hard_gate === 'FAIL' || measuredGates.value.includes('FAIL')) return 'FAIL'
  const requiredMeasured = retrievalScores.value.slice(0, 2).every((item) => item.metric?.value != null)
  const judgeConfigured = judgeResult.value?.score != null
  if (!requiredMeasured || !judgeConfigured || security.value?.status !== 'MEASURED') return 'INCOMPLETE'
  return 'PASS'
})

const scoreRingStyle = computed(() => ({
  '--score': `${Math.round((successRate.value ?? 0) * 100) * 3.6}deg`,
} as Record<string, string>))

function metricGate(item: ScoreMetric): GateState {
  const value = item.metric?.value
  if (value == null || item.threshold === undefined) return 'NOT_MEASURED'
  return (item.direction === 'max' ? value <= item.threshold : value >= item.threshold) ? 'PASS' : 'FAIL'
}

function formatPercent(value: number | null | undefined, digits = 1): string {
  return value == null ? '—' : `${(value * 100).toFixed(digits)}%`
}

function formatDate(value: string | undefined): string {
  if (!value) return '—'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(props.locale === 'zh' ? 'zh-CN' : 'en', {
    dateStyle: 'medium', timeStyle: 'short',
  }).format(date)
}

function metricWidth(value: number | null | undefined): string {
  return `${Math.max(0, Math.min(100, (value ?? 0) * 100))}%`
}

async function loadLatest() {
  loading.value = true
  loadError.value = ''
  try {
    const response = await fetch(reportUrl, { cache: 'no-store', headers: { Accept: 'application/json' } })
    if (!response.ok) throw new Error(`HTTP ${response.status}`)
    const payload: unknown = await response.json()
    if (!isEvaluationReport(payload)) throw new Error('invalid report')
    report.value = payload
    source.value = 'published'
  } catch {
    if (!report.value) loadError.value = copy.value.loadFailed
  } finally {
    loading.value = false
  }
}

function openFilePicker() {
  fileInput.value?.click()
}

async function importReport(event: Event) {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  loadError.value = ''
  try {
    const payload: unknown = JSON.parse(await file.text())
    if (!isEvaluationReport(payload)) throw new Error('invalid report')
    report.value = payload
    source.value = 'local'
  } catch {
    loadError.value = copy.value.invalidFile
  } finally {
    input.value = ''
  }
}

onMounted(loadLatest)
</script>

<template>
  <section id="evaluation" class="evaluation-dashboard">
    <div class="evaluation-heading">
      <div>
        <p class="eyebrow">{{ copy.kicker }}</p>
        <h2>{{ copy.title }}</h2>
        <p class="evaluation-lede">{{ copy.lede }}</p>
      </div>
      <div class="evaluation-actions">
        <button type="button" class="secondary-action" :disabled="loading" @click="loadLatest">{{ copy.latest }}</button>
        <button type="button" class="primary-action" @click="openFilePicker">{{ copy.import }}</button>
        <input ref="fileInput" class="visually-hidden" type="file" accept="application/json,.json" @change="importReport">
      </div>
    </div>

    <div v-if="loading && !report" class="evaluation-empty card">{{ copy.loading }}</div>
    <div v-else-if="!report" class="evaluation-empty card">
      <strong>NOT MEASURED</strong>
      <p>{{ loadError || copy.empty }}</p>
    </div>

    <template v-else>
      <div v-if="report.synthetic_fixture" class="fixture-warning" role="status">
        <strong>SYNTHETIC_FIXTURE · NOT A BENCHMARK RESULT</strong>
        <span>{{ copy.synthetic }}</span>
      </div>
      <div v-if="loadError" class="inline-error" role="alert">{{ loadError }}</div>

      <div class="score-summary">
        <article class="primary-score card">
          <div class="score-ring" :class="successRate == null ? 'unmeasured' : ''" :style="scoreRingStyle">
            <div>
              <strong>{{ formatPercent(successRate, 0) }}</strong>
              <span>{{ copy.caseSuccess }}</span>
            </div>
          </div>
          <div class="score-copy">
            <div class="score-topline">
              <span class="data-source">{{ source === 'local' ? copy.local : copy.published }}</span>
              <span class="gate-pill" :class="releaseGate.toLowerCase()">
                {{ copy.releaseGate }} · {{ releaseGate === 'INCOMPLETE' ? copy.incomplete : releaseGate }}
              </span>
            </div>
            <div class="case-counts">
              <div><strong>{{ success?.eligible_cases ?? '—' }}</strong><span>{{ copy.eligible }}</span></div>
              <div><strong>{{ success?.successful_cases ?? '—' }}</strong><span>{{ copy.successful }}</span></div>
              <div><strong>{{ success?.excluded_cases ?? '—' }}</strong><span>{{ copy.excluded }}</span></div>
            </div>
            <p class="confidence-line">
              {{ copy.confidence }} ·
              {{ successCi ? `${formatPercent(successCi[0])} – ${formatPercent(successCi[1])}` : '—' }}
            </p>
          </div>
        </article>

        <aside class="run-card card">
          <dl>
            <div><dt>{{ copy.run }}</dt><dd>{{ report.manifest?.run_id || '—' }}</dd></div>
            <div><dt>{{ copy.dataset }}</dt><dd>{{ Array.isArray(report.manifest?.dataset_version) ? report.manifest?.dataset_version.join(', ') : report.manifest?.dataset_version || '—' }}</dd></div>
            <div><dt>{{ copy.strategy }}</dt><dd>{{ report.manifest?.strategy || '—' }}</dd></div>
            <div><dt>{{ copy.measuredAt }}</dt><dd>{{ formatDate(report.manifest?.created_at) }}</dd></div>
          </dl>
        </aside>
      </div>

      <div class="metric-sections">
        <section class="metric-section card">
          <div class="metric-section-title"><span>01</span><h3>{{ copy.retrieval }}</h3><small>{{ retrieval?.eligible_cases ?? 0 }} cases</small></div>
          <div class="score-list">
            <article v-for="item in retrievalScores" :key="item.key" class="score-row">
              <div class="score-row-heading">
                <div><strong>{{ item.label }}</strong><small>{{ item.helper }}</small></div>
                <div class="score-value">
                  <strong>{{ formatPercent(item.metric?.value) }}</strong>
                  <span v-if="item.threshold !== undefined" :class="`metric-gate ${metricGate(item).toLowerCase()}`">
                    {{ metricGate(item) === 'NOT_MEASURED' ? copy.notMeasured : metricGate(item) }}
                  </span>
                </div>
              </div>
              <div class="metric-track"><i :style="{ width: metricWidth(item.metric?.value) }" /></div>
              <div class="metric-meta"><span>n={{ item.metric?.count ?? 0 }}</span><span v-if="item.threshold !== undefined">gate ≥ {{ formatPercent(item.threshold) }}</span></div>
            </article>
          </div>
        </section>

        <section class="metric-section card">
          <div class="metric-section-title"><span>02</span><h3>{{ copy.generation }}</h3><small>{{ generation?.eligible_cases ?? 0 }} cases</small></div>
          <div class="score-list">
            <article v-for="item in generationScores" :key="item.key" class="score-row">
              <div class="score-row-heading">
                <div><strong>{{ item.label }}</strong><small>{{ item.helper }}</small></div>
                <div class="score-value">
                  <strong>{{ formatPercent(item.metric?.value) }}</strong>
                  <span v-if="item.threshold !== undefined" :class="`metric-gate ${metricGate(item).toLowerCase()}`">
                    {{ metricGate(item) === 'NOT_MEASURED' ? copy.notMeasured : metricGate(item) }}
                  </span>
                </div>
              </div>
              <div class="metric-track"><i :style="{ width: metricWidth(item.metric?.value) }" /></div>
              <div class="metric-meta"><span>n={{ item.metric?.count ?? (item.metric?.value == null ? 0 : 1) }}</span><span v-if="item.threshold !== undefined">gate ≥ {{ formatPercent(item.threshold) }}</span></div>
            </article>
          </div>
        </section>
      </div>

      <div class="operational-grid">
        <section class="operational-card card">
          <div class="metric-section-title"><span>03</span><h3>{{ copy.safety }}</h3></div>
          <div class="operational-values">
            <div><span>{{ copy.hardGate }}</span><strong :class="security?.hard_gate === 'FAIL' ? 'danger' : 'safe'">{{ security?.hard_gate || copy.notMeasured }}</strong></div>
            <div><span>{{ copy.forbidden }}</span><strong>{{ security?.forbidden_retrieval_count ?? '—' }}</strong></div>
            <div><span>{{ copy.injections }}</span><strong>{{ security?.prompt_injection_compliance_count ?? '—' }}</strong></div>
          </div>
        </section>
        <section class="operational-card card">
          <div class="metric-section-title"><span>04</span><h3>{{ copy.performance }}</h3></div>
          <div class="operational-values">
            <div><span>{{ copy.p95 }}</span><strong>{{ performance?.p95_ms == null ? '—' : `${Math.round(performance.p95_ms)} ms` }}</strong></div>
            <div><span>{{ copy.errors }}</span><strong>{{ formatPercent(performance?.error_rate) }}</strong></div>
            <div><span>{{ copy.fallback }}</span><strong>{{ formatPercent(performance?.fallback_rate) }}</strong></div>
          </div>
        </section>
      </div>

      <section class="case-table-card card">
        <div class="metric-section-title"><span>05</span><h3>{{ copy.cases }}</h3><small>{{ success?.cases?.length ?? 0 }}</small></div>
        <div v-if="success?.cases?.length" class="case-table-wrap">
          <table>
            <thead><tr><th>{{ copy.caseId }}</th><th>{{ copy.result }}</th><th>{{ copy.reason }}</th></tr></thead>
            <tbody>
              <tr v-for="item in success.cases" :key="item.case_id">
                <td><code>{{ item.case_id }}</code></td>
                <td><span :class="`case-result ${item.success ? 'pass' : 'fail'}`">{{ item.success ? copy.pass : copy.fail }}</span></td>
                <td>{{ item.reasons.length ? item.reasons.join(' · ') : copy.noReason }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p v-else class="no-cases">{{ copy.noCases }}</p>
      </section>

      <p class="methodology-note">{{ copy.methodology }}</p>
    </template>
  </section>
</template>

<style scoped>
.evaluation-dashboard { display: grid; gap: 18px; }
.evaluation-heading { align-items: end; display: flex; gap: 32px; justify-content: space-between; margin-bottom: 18px; }
.evaluation-heading h2 { font-size: clamp(34px, 5vw, 56px); }
.evaluation-lede { color: #686158; line-height: 1.75; margin: 18px 0 0; max-width: 680px; }
.evaluation-actions { display: flex; flex: 0 0 auto; gap: 9px; }
.evaluation-actions button { border-radius: 1px; font-size: 11px; font-weight: 700; min-height: 41px; padding: 0 14px; }
.primary-action { background: #c9654b; border: 1px solid #c9654b; color: #fffaf4; }
.secondary-action { background: transparent; border: 1px solid #cfc6ba; color: #686158; }
.evaluation-actions button:disabled { cursor: wait; opacity: .5; }
.visually-hidden { height: 1px; margin: -1px; opacity: 0; overflow: hidden; position: absolute; width: 1px; }
.evaluation-empty { color: #817a70; min-height: 240px; padding: 62px; text-align: center; }
.evaluation-empty strong { color: #a1432e; font: 700 11px/1 ui-monospace, monospace; letter-spacing: .12em; }
.evaluation-empty p { line-height: 1.7; margin: 18px auto 0; max-width: 520px; }
.fixture-warning { align-items: center; background: #fff4df; border: 1px solid #dfbe7c; color: #745b2e; display: flex; font-size: 12px; gap: 18px; padding: 14px 17px; }
.fixture-warning strong { flex: 0 0 auto; font: 700 10px/1.4 ui-monospace, monospace; letter-spacing: .07em; }
.inline-error { background: #fff1ec; border: 1px solid #e3a38e; color: #a1432e; padding: 12px 15px; }
.score-summary { display: grid; gap: 18px; grid-template-columns: 1.45fr .75fr; }
.primary-score { align-items: center; display: grid; gap: 34px; grid-template-columns: 190px 1fr; }
.score-ring { --score: 0deg; align-items: center; aspect-ratio: 1; background: conic-gradient(#c9654b var(--score), #e6ded4 0); border-radius: 50%; display: flex; justify-content: center; padding: 12px; position: relative; }
.score-ring::before { background: #fbf9f5; border-radius: 50%; content: ''; height: 100%; width: 100%; }
.score-ring > div { align-items: center; display: flex; flex-direction: column; position: absolute; text-align: center; width: 125px; }
.score-ring strong { color: #282521; font-family: Georgia, serif; font-size: 42px; font-weight: 400; letter-spacing: -.05em; }
.score-ring span { color: #817a70; font-size: 9px; font-weight: 700; letter-spacing: .08em; margin-top: 5px; text-transform: uppercase; }
.score-ring.unmeasured { background: conic-gradient(#d8d1c7 360deg, #d8d1c7 0); }
.score-topline { align-items: center; display: flex; flex-wrap: wrap; gap: 10px; justify-content: space-between; }
.data-source { color: #817a70; font-size: 10px; letter-spacing: .08em; text-transform: uppercase; }
.gate-pill, .metric-gate, .case-result { border: 1px solid; display: inline-flex; font-size: 9px; font-weight: 800; letter-spacing: .07em; padding: 5px 7px; text-transform: uppercase; }
.gate-pill.pass, .metric-gate.pass, .case-result.pass { background: #e9f3ed; border-color: #9ec2ac; color: #3b7658; }
.gate-pill.fail, .metric-gate.fail, .case-result.fail { background: #fff0eb; border-color: #dfa18f; color: #a1432e; }
.gate-pill.incomplete, .metric-gate.not_measured { background: #f3eee6; border-color: #d5cabd; color: #817568; }
.case-counts { display: grid; gap: 1px; grid-template-columns: repeat(3, 1fr); margin-top: 24px; }
.case-counts div { background: #f1ece4; padding: 13px 12px; }
.case-counts strong, .case-counts span { display: block; }
.case-counts strong { color: #49423b; font: 400 23px/1 ui-monospace, monospace; }
.case-counts span { color: #91887c; font-size: 9px; letter-spacing: .06em; margin-top: 7px; text-transform: uppercase; }
.confidence-line { color: #817a70; font: 10px/1.5 ui-monospace, monospace; margin: 15px 0 0; }
.run-card { display: flex; }
.run-card dl { display: grid; margin: 0; width: 100%; }
.run-card dl div { border-bottom: 1px solid #e3ddd4; padding: 11px 0; }
.run-card dl div:last-child { border-bottom: 0; }
.run-card dt { color: #91887c; font-size: 9px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
.run-card dd { color: #49423b; font: 11px/1.5 ui-monospace, monospace; margin: 5px 0 0; overflow-wrap: anywhere; }
.metric-sections, .operational-grid { display: grid; gap: 18px; grid-template-columns: repeat(2, 1fr); }
.metric-section-title { align-items: baseline; border-bottom: 1px solid #e3ddd4; display: flex; gap: 10px; margin-bottom: 22px; padding-bottom: 14px; }
.metric-section-title > span { color: #b55942; font: 700 10px/1 ui-monospace, monospace; }
.metric-section-title h3 { color: #39342f; font-family: Georgia, serif; font-size: 22px; font-weight: 400; margin: 0; }
.metric-section-title small { color: #91887c; font-size: 10px; margin-left: auto; }
.score-list { display: grid; gap: 22px; }
.score-row-heading { align-items: start; display: flex; gap: 18px; justify-content: space-between; }
.score-row-heading strong, .score-row-heading small { display: block; }
.score-row-heading strong { color: #49423b; font-size: 12px; }
.score-row-heading small { color: #9a9288; font-size: 10px; line-height: 1.5; margin-top: 4px; }
.score-value { align-items: center; display: flex; gap: 8px; text-align: right; }
.score-value > strong { font: 400 19px/1 ui-monospace, monospace; }
.metric-track { background: #e8e1d8; height: 5px; margin-top: 10px; overflow: hidden; }
.metric-track i { background: #c9654b; display: block; height: 100%; min-width: 0; transition: width .4s ease; }
.metric-meta { color: #9a9288; display: flex; font: 9px/1.3 ui-monospace, monospace; justify-content: space-between; margin-top: 7px; }
.operational-values { display: grid; gap: 1px; grid-template-columns: repeat(3, 1fr); }
.operational-values div { background: #f1ece4; min-height: 84px; padding: 13px 11px; }
.operational-values span, .operational-values strong { display: block; }
.operational-values span { color: #91887c; font-size: 9px; line-height: 1.4; text-transform: uppercase; }
.operational-values strong { color: #49423b; font: 400 17px/1.2 ui-monospace, monospace; margin-top: 12px; overflow-wrap: anywhere; }
.operational-values strong.safe { color: #3b7658; }
.operational-values strong.danger { color: #a1432e; }
.case-table-wrap { overflow-x: auto; }
table { border-collapse: collapse; width: 100%; }
th { color: #91887c; font-size: 9px; letter-spacing: .08em; padding: 0 12px 10px; text-align: left; text-transform: uppercase; }
td { border-top: 1px solid #e3ddd4; color: #686158; font-size: 11px; line-height: 1.5; padding: 13px 12px; }
td code { color: #49423b; font-size: 10px; }
.no-cases { color: #91887c; font-size: 12px; margin: 0; }
.methodology-note { color: #91887c; font-size: 10px; line-height: 1.6; margin: 2px 0 0; text-align: center; }

@media (max-width: 860px) {
  .evaluation-heading { align-items: flex-start; flex-direction: column; }
  .score-summary, .metric-sections, .operational-grid { grid-template-columns: 1fr; }
}

@media (max-width: 620px) {
  .evaluation-actions { display: grid; width: 100%; }
  .primary-score { grid-template-columns: 1fr; justify-items: center; text-align: center; }
  .score-ring { width: 168px; }
  .score-copy { width: 100%; }
  .score-topline { justify-content: center; }
  .operational-values { grid-template-columns: 1fr; }
  .fixture-warning { align-items: flex-start; flex-direction: column; gap: 7px; }
}
</style>
